services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my_django_network

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my_django_network

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z-cpuv1
    container_name: my_minio_container
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - my_django_network

#  web:
#    build: .
#    restart: always
#    command: sh -c "chown -R userdj:groupdjango /app/staticfiles &&
#                    python manage.py collectstatic --noinput --clear &&
#                    python manage.py migrate &&
#                    gunicorn cloud_file_storage.wsgi:application \
#                     --bind 0.0.0.0:8000 \
#                     --user userdj \
#                     --group groupdjango \
#                     -w 1 \
#                     --reload"
#    volumes:
#      - .:/app
#      - static_volume:/app/staticfiles
#    env_file: .env
#    depends_on:
#      - db
#      - redis
#      - minio
#    networks:
#      - my_django_network
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx-server
#    restart: always
#    ports:
#      - "80:8088"
#    volumes:
#      - static_volume:/app/static_collected/:ro
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx_logs:/var/log/nginx
#    depends_on:
#      - web
#    networks:
#      - my_django_network
#
volumes:
  postgres_data:
#  static_volume:
  redis_data:
  minio_data:

networks:
  my_django_network:
    driver: bridge